#simple
#chmod 755 clean.scrpit
#chmod 755 compile.scrpit 
ghc Tutorials/Dice.hs
ghc Tutorials/FlashingHeart.hs
ghc Tutorials/LoveMeter.hs
ghc Tutorials/MicroChat.hs
ghc Tutorials/MicroChatGroup1.hs
ghc Tutorials/NameTag.hs
ghc Tutorials/SmileyButtonsA.hs
ghc Tutorials/SmileyButtonsAB.hs
ghc Games/CoinFlipper.hs
ghc Games/RockPaperScissors.hs

#A bit difficute
ghc Games/CrashyBird.hs 
ghc Games/MagicButtonTrick.hs
ghc Games/ReactionTime.hs
ghc Games/Salute.hs
ghc Games/SnapTheDot.hs